# Generated by Django 4.0.4 on 2022-06-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_Number', models.CharField(max_length=100)),
                ('Customer', models.CharField(default='', max_length=100)),
                ('Customer_Address', models.TextField(default='', max_length=300)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-Updated', '-Created'],
            },
        ),
    ]
