# Generated by Django 4.0.4 on 2022-07-03 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SWIPapp', '0002_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='Asset_QR_Img',
            field=models.ImageField(blank=True, null=True, upload_to='SWIPapp\\static\\SWIPapp\\images\\qr_codes'),
        ),
        migrations.CreateModel(
            name='AssetLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Log', models.CharField(default='', max_length=100)),
                ('ConnectedAsset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SWIPapp.asset')),
            ],
        ),
    ]
