# Generated by Django 4.0.4 on 2022-07-17 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SWIPapp', '0003_alter_asset_asset_qr_img_assetlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='Ecommerce_Price',
            field=models.FloatField(blank=True, default='0', null=True),
        ),
        migrations.CreateModel(
            name='ebayLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='', max_length=100)),
                ('SoldPrice', models.FloatField(blank=True, null=True)),
                ('SoldDate', models.CharField(default='', max_length=100)),
                ('ListingLink', models.CharField(default='', max_length=100)),
                ('ConnectedAsset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SWIPapp.asset')),
            ],
        ),
    ]
