# Generated by Django 4.0.4 on 2022-07-17 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SWIPapp', '0004_alter_asset_ecommerce_price_ebaylookup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ebayLookup',
        ),
    ]
