# Generated by Django 4.0.4 on 2022-07-17 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SWIPapp', '0005_delete_ebaylookup'),
    ]

    operations = [
        migrations.CreateModel(
            name='ebayLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='', max_length=100)),
                ('SoldPrice', models.FloatField(blank=True, null=True)),
                ('SoldDate', models.CharField(default='', max_length=100)),
                ('ListingLink', models.CharField(default='', max_length=100)),
                ('ConnectedAsset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SWIPapp.asset')),
            ],
        ),
    ]
