# Generated by Django 4.0.4 on 2022-07-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SWIPapp', '0006_ebaylookup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ListName', models.CharField(default='', max_length=100)),
                ('AttachedAssets', models.ManyToManyField(to='SWIPapp.asset')),
            ],
        ),
    ]
