# Generated by Django 4.0.4 on 2022-07-30 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SWIPapp', '0008_lists_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lists',
            options={'ordering': ['-Created']},
        ),
    ]
