# Generated by Django 4.0.4 on 2022-08-02 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SWIPapp', '0009_alter_lists_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='HDD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Asset_QR', models.CharField(default='', max_length=100)),
                ('Asset_QR_Img', models.ImageField(blank=True, null=True, upload_to='main\\static\\lessapp\\images\\qr_codes')),
                ('Storage', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('Storage_Serial_Number', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('Storage_Capacity', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('Wipe_Method', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('Wipe_Start_Time', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('Wipe_End_Time', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('Wipe_Result', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('Created', models.DateTimeField(auto_now_add=True, null=True)),
                ('Updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('Order_Number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SWIPapp.order')),
            ],
            options={
                'ordering': ['-Updated', '-Created'],
            },
        ),
    ]
