# Generated by Django 4.0.5 on 2022-10-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SWIPapp', '0011_asset_ecommerce_connectivity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='Screen_Resolution',
            field=models.CharField(blank=True, default='N/A', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='Screen_Size',
            field=models.CharField(blank=True, default='N/A', max_length=10, null=True),
        ),
    ]
