# Generated by Django 4.0.5 on 2022-11-17 13:49

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('SWIPapp', '0012_asset_screen_resolution_alter_asset_screen_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='Ecommerce_SuitableFor',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Casual Computing', 'Casual Computing'), ('Gaming', 'Gaming'), ('Office', 'Office'), ('Workstation', 'Workstation'), ('Graphic Design', 'Graphic Design')], default='Casual Computing', max_length=57),
        ),
    ]
