# Generated by Django 4.1.6 on 2023-03-09 10:12

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('SWIPapp', '0013_alter_asset_ecommerce_suitablefor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='Ecommerce_Connectivity',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('USB 2.0', 'USB 2.0'), ('USB 3.0', 'USB 3.0'), ('USB-C', 'USB-C'), ('VGA', 'VGA'), ('HDMI', 'HDMI'), ('Display-Port', 'Display-Port'), ('DVI', 'DVI'), ('DVI-D', 'DVI-D')], default='USB 2.0', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='Ecommerce_Features',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Backlit Keyboard', 'Backlit Keyboard'), ('Bluetooth', 'Bluetooth'), ('Built-in Camera', 'Built-in Camera'), ('Built-in Microphone', 'Built-in Microphone'), ('Touchscreen', 'Touchscreen'), ('Wi-Fi', 'Wi-Fi'), ('Memory Card(s) Reader', 'Memory Card(s) Reader'), ('SD Card Slot', 'SD Card Slot'), ('Touch ID', 'Touch ID')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='Ecommerce_Item_Description',
            field=models.TextField(blank=True, default='', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='Ecommerce_SuitableFor',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Casual Computing', 'Casual Computing'), ('Gaming', 'Gaming'), ('Office', 'Office'), ('Workstation', 'Workstation'), ('Graphic Design', 'Graphic Design')], default='Casual Computing', max_length=150),
        ),
    ]
