# Generated by Django 4.1.6 on 2023-03-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SWIPapp', '0014_alter_asset_ecommerce_connectivity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='Ecommerce_Item_Description',
            field=models.TextField(blank=True, default='', max_length=20000, null=True),
        ),
    ]
